steps:
- name: 'node:16'
  entrypoint: 'npm'
  args: ['install']

- name: 'node:16'
  entrypoint: 'npm'
  args: ['test']

- name: 'node:16'
  entrypoint: 'npm'
  args: ['run', 'build']
artifacts:
  npmPackages:
  - repository: 'https://northamerica-northeast1-npm.pkg.dev/spiritual-aloe-397911/Prihantoedi/be-chat-app-firebase'
    packagePath: '.'
